name: Build image and push to Artifact Registry of GCP
on: 
  push:
    branches: 
      - main
 
jobs:
  build-push-artifact:
    name : Build and push Artifact Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: build Docker Image
      run: docker build -t pipe_agrofit:latest .
    
    - name: Configure Docker Client of Gcloud
      run:  |-
        gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
    
    - name: Push Docker Image to Artifact Registry 
      env:
        GIT_TAG: v0.1.0
      run:  |-
        docker tag pipe_agrofit:latest us-east1-docker.pkg.dev/ornate-bond-422513-s9/cicd-repo/pipe_agrofit:latest
        docker push us-east1-docker.pkg.dev/ornate-bond-422513-s9/cicd-repo/pipe_agrofit:latest